name: Docker CD

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract version from tag (if any)
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mspr-products-api:${{ env.VERSION }} -f MSPR-bloc-4-products/Dockerfile .

      - name: Push versioned image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mspr-products-api:${{ env.VERSION }}

      - name: Tag as latest (only on master)
        if: github.ref == 'refs/heads/master' && env.VERSION != 'latest'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/mspr-products-api:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/mspr-products-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mspr-products-api:latest
